    aircraft_carrier  bathtub        broccoli    cat          crown         eye            garden        hospital         light_bulb  mountain    parachute      potato          scorpion      sock         sun                      toothbrush       wheel
airplane          beach          broom       ceiling_fan  cruise_ship   eyeglasses     garden_hose   hot_air_balloon  lighter     mouse       parrot         power_outlet    screwdriver   speedboat    swan                     toothpaste       windmill
alarm_clock       bear           bucket      cello        cup           face           giraffe       hot_dog          lighthouse  moustache   passport       purse           sea_turtle    spider       sweater                  tornado          wine_bottle
ambulance         beard          bulldozer   cell_phone   diamond       fan            goatee        hot_tub          lightning   mouth       peanut         rabbit          see_saw       spoon        swing_set                tractor          wine_glass
angel             bed            bus         chair        dishwasher    feather        golf_club     hourglass        line        mug         pear           raccoon         shark         spreadsheet  sword                    traffic_light    wristwatch
animal_migration  bee            bush        chandelier   diving_board  fence          grapes        house            lion        mushroom    peas           radio           sheep         square       syringe                  train            yoga
ant               belt           butterfly   church       dog           finger         grass         house_plant      lipstick    nail        pencil         rain            shoe          squiggle     table                    tree             zebra
anvil             bench          cactus      circle       dolphin       fire_hydrant   guitar        hurricane        lobster     necklace    penguin        rainbow         shorts        squirrel     teapot                   triangle         zigzag
apple             bicycle        cake        clarinet     donut         fireplace      hamburger     ice_cream        lollipop    nose        piano          rake            shovel        stairs       teddy-bear               trombone
arm               bird           calculator  clock        door          firetruck      hammer        jacket           mailbox     ocean       pickup_truck   remote_control  sink          star         telephone                truck
asparagus         birthday_cake  calendar    cloud        dragon        fish           hand          jail             map         octagon     picture_frame  rhinoceros      skateboard    steak        television               trumpet
axe               blackberry     camel       coffee_cup   dresser       flamingo       harp          kangaroo         marker      octopus     pig            rifle           skull         stereo       tennis_racquet           t-shirt
backpack          blueberry      camera      compass      drill         flashlight     hat           key              matches     onion       pillow         river           skyscraper    stethoscope  tent                     umbrella
banana            book           camouflage  computer     drums         flip_flops     headphones    keyboard         megaphone   oven        pineapple      roller_coaster  sleeping_bag  stitches     The_Eiffel_Tower         underwear
bandage           boomerang      campfire    cookie       duck          floor_lamp     hedgehog      knee             mermaid     owl         pizza          rollerskates    smiley_face   stop_sign    The_Great_Wall_of_China  van
barn              bottlecap      candle      cooler       dumbbell      flower         helicopter    knife            microphone  paintbrush  pliers         sailboat        snail         stove        The_Mona_Lisa            vase
baseball          bowtie         cannon      couch        ear           flying_saucer  helmet        ladder           microwave   paint_can   police_car     sandwich        snake         strawberry   tiger                    violin
baseball_bat      bracelet       canoe       cow          elbow         foot           hexagon       lantern          monkey      palm_tree   pond           saw             snorkel       streetlight  toaster                  washing_machine
basket            brain          car         crab         elephant      fork           hockey_puck   laptop           moon        panda       pool           saxophone       snowflake     string_bean  toe                      watermelon
basketball        bread          carrot      crayon       envelope      frog           hockey_stick  leaf             mosquito    pants       popsicle       school_bus      snowman       submarine    toilet                   waterslide
bat               bridge         castle      crocodile    eraser        frying_pan     horse         leg              motorbike   paper_clip  postcard       scissors        soccer_ball   suitcase     tooth                    whale